package Staff;


import Main.Data;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fatih
 */
public class ControlData extends javax.swing.JFrame {
    
    ArrayList<Barang> data;
    String header[] = new String[]{"ID", "Nama", "Tipe", "Detail", "Tanggal"};
    DefaultTableModel defaultTableModel;
    int row, col;
    

    /**
     * Creates new form GUIReminder
     */
    public ControlData() {
        initComponents();
        data = new ArrayList<>();
        defaultTableModel = new DefaultTableModel(header,0);
        TableData.setModel(defaultTableModel);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelData = new javax.swing.JLabel();
        LogsiticIcon = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        NamaLabel = new javax.swing.JLabel();
        TipeLabel = new javax.swing.JLabel();
        BoxTipe = new javax.swing.JComboBox<>();
        NamaField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        DetailLabel = new javax.swing.JLabel();
        ScrollPanel = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        TanggalLabel = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        DetailArea = new javax.swing.JTextField();
        Open = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(550, 650));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        LabelData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelData.setText("Logistic Data");

        LogsiticIcon.setIcon(new javax.swing.ImageIcon("D:\\belajar\\GUIDemo\\src\\asset\\logistic.png")); // NOI18N

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(LogsiticIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelData)
                .addGap(151, 151, 151)
                .addComponent(Back)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogsiticIcon)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelData)
                        .addComponent(Back)))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Delete)
                    .addComponent(Update))
                .addContainerGap())
        );

        IDLabel.setText("ID");

        NamaLabel.setText("Nama");

        TipeLabel.setText("Tipe");

        BoxTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F&B", "Technology", "Health", "Transportation" }));

        DetailLabel.setText("Detail");

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Tipe", "Detail", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        ScrollPanel.setViewportView(TableData);
        if (TableData.getColumnModel().getColumnCount() > 0) {
            TableData.getColumnModel().getColumn(0).setResizable(false);
            TableData.getColumnModel().getColumn(1).setMaxWidth(40);
            TableData.getColumnModel().getColumn(3).setMaxWidth(120);
            TableData.getColumnModel().getColumn(4).setResizable(false);
            TableData.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        TanggalLabel.setText("Tanggal");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Open)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Save)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel)
                            .addComponent(NamaLabel)
                            .addComponent(DetailLabel)
                            .addComponent(TanggalLabel)
                            .addComponent(TipeLabel))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NamaField)
                            .addComponent(BoxTipe, 0, 280, Short.MAX_VALUE)
                            .addComponent(IDField)
                            .addComponent(DateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DetailArea))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(DetailLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipeLabel))
                        .addGap(26, 26, 26)
                        .addComponent(DetailArea, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TanggalLabel))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Open))
                .addGap(18, 18, 18)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        int ID = Integer.parseInt(IDField.getText());
        String nama = NamaField.getText();
        String tipe = BoxTipe.getSelectedItem().toString();
        String detail = DetailArea.getText();
        String date = df.format(DateChooser.getDate());
        Barang dataWarehouse = new Barang(ID, nama, tipe, detail, date);
        data.add(dataWarehouse);
        defaultTableModel.setRowCount(0);
        for(int i = 0; i < data.size() ; i ++){
            Object[] obj = {
                data.get(i).id, 
                data.get(i).nama,
                data.get(i).tipe,
                data.get(i).detail,
                data.get(i).date      
            };
            defaultTableModel.addRow(obj);
        }
        JOptionPane.showMessageDialog(null,"Data Added"); 
        clearField();
    }//GEN-LAST:event_AddActionPerformed

    private void clearField(){
       IDField.setText("");
       NamaField.setText("");
       BoxTipe.setSelectedIndex(0);
       DetailArea.setText("");
    }
    
    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked
        // TODO add your handling code here:
        row = TableData.getSelectedRow();
        col = TableData.getColumnCount();
        IDField.setText(defaultTableModel.getValueAt(row,0).toString());
        NamaField.setText(defaultTableModel.getValueAt(row,1).toString());
        String tipe = defaultTableModel.getValueAt(row,2).toString();
        for(int i = 0; i < BoxTipe.getItemCount(); i ++ ){
            if(BoxTipe.getItemAt(i).equalsIgnoreCase(tipe)){
                BoxTipe.setSelectedIndex(i);
            }
        }
        DetailArea.setText(defaultTableModel.getValueAt(row, 3).toString());
    }//GEN-LAST:event_TableDataMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        DateFormat Updatedf = new SimpleDateFormat("dd-MM-yyyy");
        int UpdateID = Integer.parseInt(IDField.getText());
        String Updatenama = NamaField.getText();
        String Updatetipe = BoxTipe.getSelectedItem().toString();
        String Updatedetail = DetailArea.getText();
        String Updatedate = Updatedf.format(DateChooser.getDate());
        data.get(row).id = UpdateID;
        data.get(row).nama = Updatenama;
        data.get(row).tipe = Updatetipe;
        data.get(row).detail = Updatedetail;
        data.get(row).date = Updatedate;       
        defaultTableModel.setRowCount(0);
        for(int i = 0; i < data.size() ; i ++){
            Object[] obj = {
                data.get(i).id, 
                data.get(i).nama,
                data.get(i).tipe,
                data.get(i).detail,
                data.get(i).date      
            };
            defaultTableModel.addRow(obj);
        }
        JOptionPane.showMessageDialog(null,"Data Update"); 
        clearField();
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Delete This Data", "Delete", dialogButton);
        if(dialogButton == 0){
            defaultTableModel.removeRow(row);
            data.remove(row);
            defaultTableModel.setRowCount(0);
            for(int i = 0; i < data.size(); i++){
                Object[] obj = {
                    data.get(i).id, 
                    data.get(i).nama, 
                    data.get(i).tipe,
                    data.get(i).detail,
                    data.get(i).date
                };
                defaultTableModel.addRow(obj);
            }
            clearField();
        }else{
            
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file save");
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = fileChooser.getSelectedFile();
            //lets write to file
         
            try {
                 FileWriter fw = new FileWriter(fileToSave);
                BufferedWriter bw = new BufferedWriter(fw);
                for (int i = 0; i < TableData.getRowCount(); i++) {
                    for (int j = 0; j < TableData.getColumnCount(); j++) {
                        //write
                        bw.write(TableData.getValueAt(i, j).toString()+" ");
                    }
                    bw.newLine();//record per line 
                }
                JOptionPane.showMessageDialog(this, "SUCCESSFULLY LOADED","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
                bw.close();
                fw.close();
            } catch (IOException ex) {
               JOptionPane.showMessageDialog(this, "ERROR","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
            }
            
        }



    }//GEN-LAST:event_SaveActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify to Open");
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection == JFileChooser.APPROVE_OPTION){
        File fileToOpen = fileChooser.getSelectedFile();
        
        try{
            FileReader filereader = new FileReader(fileToOpen);
             BufferedReader bufferedReader = new BufferedReader(filereader);
             
             DefaultTableModel model = (DefaultTableModel)TableData.getModel();
             Object[] tableLine = bufferedReader.lines().toArray();
             
            for (Object tableLine1 : tableLine) {
                String[] dataRow = tableLine1.toString().split(" ");
                model.addRow(dataRow);
            }
        }catch(IOException e){
             JOptionPane.showMessageDialog(this, "ERROR","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
       }
    }//GEN-LAST:event_OpenActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        LogisticPage backPage = new LogisticPage();
        backPage.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ControlData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JComboBox<String> BoxTipe;
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField DetailArea;
    private javax.swing.JLabel DetailLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel LabelData;
    private javax.swing.JLabel LogsiticIcon;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JButton Open;
    private javax.swing.JButton Save;
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JTable TableData;
    private javax.swing.JLabel TanggalLabel;
    private javax.swing.JLabel TipeLabel;
    private javax.swing.JButton Update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}


class Barang extends Data {
   String tipe, detail, date;
 
    public Barang(int id, String nama, String tipe, String detail, String date){
       super(id, nama);
        this.tipe = tipe;
        this.detail = detail;
        this.date = date;
    }
}